import type { Metadata } from "next";
import { Edu_VIC_WA_NT_Beginner, Inter } from "next/font/google";
import Heder from '../components/header'
import "./globals.css";
import { minify } from "next/dist/build/swc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Heder />
        {children}</body>
    </html>
  );
}




